security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            anonymous: true
            provider: users
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   logout
                target: login