homepage:
    path:     /
    defaults: { _controller: App\Controller\HomeController::home }

#Ads admin
admin_ads_index:
    path:     /admin/ads/{page}
    defaults:
        _controller: App\Controller\AdminAdController::index
        page: 1
    requirements:
        page: \d+

admin_ads_edit:
    path:     /admin/ads/{id}/edit
    defaults: { _controller: App\Controller\AdminAdController::edit }
    requirements:
        id: \d+

admin_ads_delete:
    path:     /admin/ads/{id}/delete
    defaults: { _controller: App\Controller\AdminAdController::delete }
    requirements:
        id: \d+

#Comment admin
admin_comments_index:
    path:     /admin/comments/{page}
    defaults: 
        _controller: App\Controller\AdminCommentController::index
        page: 1
    requirements:
        page: \d+
    
admin_comments_edit:
    path:     /admin/comments/{id}/edit
    defaults: { _controller: App\Controller\AdminCommentController::edit }
    requirements:
        id: \d+

admin_comments_delete:
    path:     /admin/comments/{id}/delete
    defaults: { _controller: App\Controller\AdminCommentController::delete }
    requirements:
        id: \d+

#Ads client
ads_create:
    path:     /ads/new
    defaults: { _controller: App\Controller\AdController::create }
    
ads_index:
    path:     /ads
    defaults: { _controller: App\Controller\AdController::index }

ads_show:
    path:     /ads/{slug}
    defaults: { _controller: App\Controller\AdController::show }
    requirements:
        slug: ([a-z-0-9]*)

ads_edit:
    path:     /ads/{slug}/edit
    defaults: { _controller: App\Controller\AdController::edit }
    requirements:
        slug: ([a-z-0-9]*)

ads_delete:
    path:     /ads/{slug}/delete
    defaults: { _controller: App\Controller\AdController::delete }
    requirements:
        slug: ([a-z-0-9]*)

#Account
login:
    path: /login
    defaults: { _controller: App\Controller\AccountController::login }

logout:
    path: /logout

register:
    path: /register
    defaults: { _controller: App\Controller\AccountController::register }

account_profil:
    path: /account/profil
    defaults: { _controller: App\Controller\AccountController::profil }

account_password:
    path: /account/password-update
    defaults: { _controller: App\Controller\AccountController::updatePassword }

account_index:
    path: /account
    defaults: { _controller: App\Controller\AccountController::myAccount }

account_bookings:
    path: /account/bookings
    defaults: { _controller: App\Controller\AccountController::bookings }

#User
user_show:
    path: /user/{slug}
    defaults: { _controller: App\Controller\UserController::index }

#Booking
booking_create:
    path: /ads/{slug}/book
    defaults: { _controller: App\Controller\BookingController::book }

booking_show:
    path:     /booking/{id}
    defaults: { _controller: App\Controller\BookingController::show }
    requirements:
        id: \d+

#Booking admin
admin_bookings_index:
    path:     /admin/bookings/{page}
    defaults: 
        _controller: App\Controller\AdminBookingController::index
        page: 1
    requirements:
        page: \d+

admin_booking_edit:
    path:     /admin/bookings/{id}/edit
    defaults: { _controller: App\Controller\AdminBookingController::edit }
    requirements:
        id: \d+

admin_booking_delete:
    path:     /admin/bookings/{id}/delete
    defaults: { _controller: App\Controller\AdminBookingController::delete }
    requirements:
        id: \d+